cluster:
  control_planes: 1
  workers: 2
  network: "192.168.56"
  control_plane_start_ip: 10
  worker_start_ip: 20

vm:
  box: "bento/ubuntu-24.04"
  control_plane:
    cpus: 2
    memory: 4096
  worker:
    cpus: 2
    memory: 3072

kubernetes:
  minor_version: "v1.34"
  pod_cidr: "10.244.0.0/16"
