---
- name: Configure Kubernetes nodes
  hosts: all
  become: true
  roles:
    - common

- name: Initialize Kubernetes control plane
  hosts: control_plane
  become: true
  roles:
    - control_plane

- name: Join Kubernetes workers
  hosts: workers
  become: true
  roles:
    - worker
