---
- name: Prepare all Kubernetes nodes
  hosts: all
  become: true
  roles:
    - common

- name: Initialize control plane
  hosts: ai-k8s-cp1
  become: true
  roles:
    - control_plane

- name: Join workers
  hosts: "ai-k8s-worker*"
  become: true
  roles:
    - worker
