---
- name: Wait for control plane join command
  ansible.builtin.wait_for:
    path: /vagrant/join-command.sh
    timeout: 600

- name: Join worker to Kubernetes cluster
  ansible.builtin.command: sh /vagrant/join-command.sh
  args:
    creates: /etc/kubernetes/kubelet.conf
